#!/bin/bash

# list used and new bitcoin addresses
echo
echo "Current Wallet Addresses"
bitcoin-cli getaddressesbylabel "" | grep ": {" | cut -d \" -f2 | cut -d { -f2

echo
echo "Used Receiving Addresses"
bitcoin-cli listreceivedbyaddress | grep address | cut -d : -f2 | cut -d \" -f2

echo

bitcoin-cli getaddressesbylabel "" | grep ": {" | cut -d \" -f2 | cut -d { -f2 > /tmp/addresses1
bitcoin-cli listreceivedbyaddress | grep address | cut -d : -f2 | cut -d \" -f2 > /tmp/addresses2

echo "Never Used Addresses"
diff /tmp/addresses1 /tmp/addresses2 | grep \< | cut -d \< -f2 | sed 's/^[ \t]*//;s/[ \t]*$//'

echo
