#!/bin/bash
# list used and new bitcoin addresses

bitcoin_cli() {
    command bitcoin-cli -datadir=/mnt/files.ntfs/Crypto/Bitcoin/ -conf=bitcoin-pruned.conf "$@"
}

echo
echo "Current Wallet Addresses"
bitcoin_cli getaddressesbylabel "" | jq -r 'keys[]'

echo
echo "Used Receiving Addresses"
bitcoin_cli listreceivedbyaddress | jq -r '.[].address'

echo

bitcoin_cli getaddressesbylabel "" | jq -r 'keys[]' \
    > /tmp/addresses1

bitcoin_cli listreceivedbyaddress | jq -r '.[].address' \
    > /tmp/addresses2

echo "Never Used Addresses"
comm -23 <(sort /tmp/addresses1) <(sort /tmp/addresses2)

echo
